import type { Origin01InvitationData } from './origin01ContentTypes'

export const maiaInvitationData = {
  id: 'origin01-maia-2026',
  code: 'LMN-015-002',
  internalName: 'Mis 15 de Maia — 17 de octubre de 2026',
  templateId: 'origin01',
  lifecycleStatus: 'review',
  audience: 'protagonist',
  eventType: 'quince',
  themeVariant: 'origin01-ivory',
  event: {
    name: 'Maia',
    celebrationLabel: 'Mis 15 años',
    startsAt: '2026-10-17T21:30:00-03:00',
    endsAt: '2026-10-18T04:00:00-03:00',
    timeZone: 'America/Argentina/Buenos_Aires',
    venue: 'Salón Sin Fronteras',
    address: 'Almafuerte 3515, San Justo, Buenos Aires',
  },
  identities: [{ displayName: 'Maia', role: 'protagonist' }],
  presentation: { showTemplateBranding: false },
  modules: [
    { moduleId: 'prelude', enabled: true },
    { moduleId: 'hero', enabled: true },
    { moduleId: 'countdown', enabled: true },
    { moduleId: 'story', enabled: true },
    { moduleId: 'eventDetails', enabled: true },
    { moduleId: 'schedule', enabled: false },
    { moduleId: 'weather', enabled: false },
    { moduleId: 'dressCode', enabled: true },
    { moduleId: 'gallery', enabled: true },
    { moduleId: 'instagram', enabled: false },
    { moduleId: 'trivia', enabled: false },
    { moduleId: 'gifts', enabled: true },
    { moduleId: 'rsvp', enabled: true },
    { moduleId: 'closing', enabled: true },
  ],
  media: [
    {
      id: 'maia-white-dress',
      kind: 'image',
      src: '/images/maia/maia-vestido-blanco.jpg',
      alt: 'Maia de niña con un vestido blanco, dando sus primeros pasos en un jardín',
      title: 'Una historia que creció conmigo',
    },
    {
      id: 'maia-flower',
      kind: 'image',
      src: '/images/maia/maia-flor.jpg',
      alt: 'Maia de niña sosteniendo una flor blanca en un jardín',
      title: 'Recuerdos para guardar',
    },
    {
      id: 'maia-gift',
      kind: 'image',
      src: '/images/maia/regalo-marfil-dorado.webp',
      alt: 'Caja de regalo marfil con un lazo beige y detalles dorados',
      title: 'Un detalle especial',
      fit: 'contain',
    },
    { id: 'music', kind: 'audio', src: '/audio/origin-01-demo.mp3', title: 'Música de fondo' },
  ],
  content: {
    prelude: {
      eyebrow: 'Una noche muy especial',
      title: 'Hola, Maia.',
      body: 'Hay momentos que imaginamos durante mucho tiempo y recuerdos que elegimos guardar para siempre.',
      reveal: 'Mis 15 años',
      question: '¿Estás lista para vivirlos?',
      actionLabel: 'Estoy lista',
      soundHint: 'La música comienza al continuar',
    },
    envelope: {
      eyebrow: 'Una invitación para vos',
      heading: 'Hay momentos que merecen ser compartidos.',
      monogram: 'M',
      instruction: 'Tocá el sello para abrir',
    },
    hero: {
      dateLabel: '17 de octubre de 2026',
      phrase: 'Una historia que creció conmigo.',
      scrollHint: 'Deslizá para descubrir ↓',
      imageMediaId: 'maia-white-dress',
    },
    countdown: {
      eyebrow: 'Cada vez falta menos',
      heading: 'La cuenta regresiva ya empezó.',
      completedMessage: 'Llegó el gran día. Gracias por ser parte.',
    },
    story: {
      eyebrow: 'Recuerdos que quedan',
      message: 'Hay historias y personas que no voy a olvidar, y recuerdos como este que siempre voy a guardar. Porque son parte de mi vida, es mi deseo que compartan conmigo este día tan especial.',
      signature: 'Maia',
    },
    eventDetails: {
      eyebrow: 'Cuándo y dónde',
      heading: 'Nos encontramos para celebrar.',
      dateLabel: '17 de octubre de 2026',
      timeLabel: '21:30 a 04:00',
      venueLabel: 'Lugar',
      mapActionLabel: 'Ver ubicación',
      calendarActionLabel: 'Agendar fecha',
      calendarDescription: 'Mis 15 años de Maia.\n\nSalón Sin Fronteras — Almafuerte 3515, San Justo.',
    },
    schedule: {
      eyebrow: 'La noche',
      heading: 'Un momento para celebrar.',
      introduction: 'Nos encontramos a las 21:30 para compartir juntos esta noche especial.',
      moments: [],
    },
    weather: {
      eyebrow: 'El clima de ese día',
      heading: 'Para que llegues preparado.',
      introduction: 'Cuando se acerque la fecha, acá vas a encontrar el pronóstico.',
      location: {
        name: 'San Justo',
        country: 'Argentina',
        latitude: -34.6766,
        longitude: -58.5605,
        timezone: 'America/Argentina/Buenos_Aires',
      },
    },
    dressCode: {
      eyebrow: 'Dress code',
      title: 'Elegante',
      description: 'Queremos compartir una noche especial, elegante y llena de alegría.',
      note: 'Los colores dorado, plateado, champagne, bordó y violeta están reservados para Maia.',
      imageMediaId: 'maia-white-dress',
    },
    gallery: {
      eyebrow: 'Una historia que creció',
      heading: 'Recuerdos que siempre voy a guardar.',
      images: [
        { mediaId: 'maia-white-dress', caption: 'Mis primeros pasos' },
        { mediaId: 'maia-flower', caption: 'Momentos que viven en mí' },
      ],
    },
    community: {
      eyebrow: 'Compartamos la noche',
      heading: 'Cada recuerdo cuenta.',
      introduction: 'Guardemos juntos los momentos de esta celebración.',
      instagram: { enabled: false, handle: '', actionLabel: 'Ver en Instagram' },
      hashtag: { enabled: false, value: '', actionLabel: 'Copiar hashtag', copiedLabel: 'Hashtag copiado' },
      album: { enabled: false, url: '', invitation: '', actionLabel: 'Abrir álbum compartido' },
    },
    trivia: {
      protagonistName: 'Maia',
      accessibleTitle: 'Trivia sobre Maia',
      introEyebrow: 'Entre nosotros…',
      title: '¿Cuánto conocés a Maia?',
      description: 'Una pequeña trivia para compartir.',
      primaryActionLabel: 'Comenzar',
      questionMetaLabel: 'Pregunta',
      nextLabel: 'Siguiente',
      resultLabel: 'Ver resultado',
      replayLabel: 'Volver a jugar',
      scoreTotalLabel: '/ 0 respuestas correctas',
      questions: [],
      resultTiers: [],
      revealTitle: 'Gracias por jugar',
      revealMessage: 'Nos vemos en la fiesta.',
      revealSignature: 'Maia',
    },
    gifts: {
      eyebrow: 'Un detalle',
      title: 'Regalos',
      description: 'Si deseás hacerme un regalo, podés entregarlo el día del evento o utilizar los datos que figuran a continuación.',
      accountHolder: 'Maia Fernández',
      bankName: 'Mercado Pago',
      accountLabel: 'Alias',
      accountValue: 'maia.modroff',
      demoNote: 'CVU: 0000003100019656683525',
      imageMediaId: 'maia-gift',
    },
    rsvp: {
      eyebrow: 'Tu presencia es muy importante',
      title: 'Confirmá tu asistencia',
      description: 'Por favor, confirmá tu asistencia antes del 4 de octubre.',
      actionLabel: 'Confirmar aquí',
      recipientPhone: '5491178205507',
      message: 'Hola, confirmo mi asistencia a los 15 años de Maia.',
    },
    closing: {
      eyebrow: 'Nos vemos muy pronto',
      title: 'Gracias por ser parte de este momento tan especial.',
      signature: 'Maia',
      imageMediaId: 'maia-flower',
      sharePrompt: 'Compartí la invitación con quienes van a ser parte de esta noche.',
      shareActionLabel: 'Compartir invitación',
      shareTitle: 'Mis 15 años de Maia',
      shareText: 'Te invito a compartir conmigo una noche muy especial.',
    },
    music: { mediaId: 'music' },
  },
  createdAt: '2026-10-02T02:20:00.000Z',
  updatedAt: '2026-10-02T02:20:00.000Z',
} satisfies Origin01InvitationData
